[package]
name = "nip41-proto0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
rand = "0.8.5"
secp256k1 = { version = "0.27.0", features = ["rand", "bitcoin-hashes"]}
